export default {
	'480pto720pUpscale': 'This video is upscaled from 480p to 720p so that the video can be viewed in 60 FPS.',
	'480pto1080pUpscale': 'This video is upscaled from 480p to 1080p so that the video can be viewed in 60 FPS.',
	'to720pUpscale': 'This video is upscaled to 720p so that the video can be viewed in 60 FPS.',
	'to1080pUpscale': 'This video is upscaled to 1080p so that the video can be viewed in 60 FPS.',
	'480pto720pUpscaleGameplay': 'The gameplay is upscaled from 480p to 720p so that the video can be viewed in 60 FPS.',
	'480pto1080pUpscaleGameplay': 'The gameplay is upscaled from 480p to 1080p so that the video can be viewed in 60 FPS.',
	'to720pUpscaleGameplay': 'The gameplay is upscaled to 720p so that the video can be viewed in 60 FPS.',
	'to1080pUpscaleGameplay': 'The gameplay is upscaled to 1080p so that the video can be viewed in 60 FPS.',
	'audioReplaced': 'The audio has been replaced/rebuilt manually due to issues on recording. Some audio elements may be lost. Apologizes for the inconvenience.',
	'audioAddedFromSilent': 'The audio has been added in post due to issues on recording. Some audio elements may be lost. Apologizes for the inconvenience.',
	'audioReplacedPrivacy': 'The audio has been replaced/rebuilt manually due to privacy issues. Some audio elements may be lost. Apologizes for the inconvenience.',
	'audioMuted': 'The video is muted due to issues on recording. Apologizes for the inconvenience.',
	'audioMutedCopyright': 'The video is muted due to copyrighted music that is played. Apologizes for the inconvenience.',
	'audioMutedPrivacy': 'The video is muted for privacy. Apologizes for the inconvenience.',
}